DROP TABLE IF EXISTS execution_items;
DROP TABLE IF EXISTS test_executions;
DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS mst_timezone;
DROP TABLE IF EXISTS mst_frequency;

CREATE TABLE mst_frequency (
    frequency_id    SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frequency_code  VARCHAR(20) NOT NULL UNIQUE,
    frequency_name  VARCHAR(50) NOT NULL
);



CREATE TABLE mst_timezone (
    timezone_id     SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timezone_code   VARCHAR(100) NOT NULL UNIQUE,
    timezone_name   VARCHAR(100)
);


CREATE TABLE schedules (
    schedule_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frequency_id     SMALLINT,
    schedule_time    TIME NOT NULL,
    timezone_id      SMALLINT NOT NULL,
    active           BOOLEAN NOT NULL DEFAULT TRUE,
    recurring        BOOLEAN NOT NULL DEFAULT FALSE,
    run_at           TIMESTAMP,
    last_run_at      TIMESTAMP,

    FOREIGN KEY (frequency_id)
        REFERENCES mst_frequency(frequency_id),

    FOREIGN KEY (timezone_id)
        REFERENCES mst_timezone(timezone_id)
);

CREATE TABLE test_executions (
    execution_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    test_id           VARCHAR(100),

    run_type          VARCHAR(20) NOT NULL
        CHECK (run_type IN ('ADHOC','SCHEDULED')),

    status            VARCHAR(20) NOT NULL,

    error_message     CLOB
,

    schedule_id       BIGINT,

    started_at        TIMESTAMP,
    finished_at       TIMESTAMP,

    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    passed            INT DEFAULT 0,
    failed            INT DEFAULT 0,
    error             INT DEFAULT 0,
    skipped           INT DEFAULT 0,
    total             INT DEFAULT 0,

    FOREIGN KEY (schedule_id)
        REFERENCES schedules(schedule_id)
);

CREATE TABLE execution_items (
    item_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    exec_case_id       VARCHAR(100),
    exec_case_name     VARCHAR(255),

    exec_script        CLOB,

    schedule_id        BIGINT,
    execution_id       BIGINT,

    script_order       INT,

    status             VARCHAR(20),

    error              CLOB
,

    duration_seconds   INT,

    FOREIGN KEY (schedule_id)
        REFERENCES schedules(schedule_id),

    FOREIGN KEY (execution_id)
        REFERENCES test_executions(execution_id)
);

CREATE INDEX idx_execution_test_id
    ON test_executions(test_id);

CREATE INDEX idx_execution_status
    ON test_executions(status);

CREATE INDEX idx_execution_schedule
    ON test_executions(schedule_id);


ALTER TABLE execution_items
ADD CONSTRAINT uq_execution_script_order
UNIQUE (execution_id, script_order);
